### PR TITLE
Wallet Manager Style

### PR DESCRIPTION
**Pull request by hugbed**
Do some CSS work on the wallet manager. (tested on chrome, firefox, safari)
There might be some dead code (hideable and stuff) but the new stuff works.

Here are some snapshots:

screen shot 2017-03-24 at 10 46 17 pm
screen shot 2017-03-24 at 10 46 23 pm
screen shot 2017-03-24 at 10 46 26 pm
screen shot 2017-03-24 at 10 46 30 pm
screen shot 2017-03-24 at 10 46 33 pm
screen shot 2017-03-24 at 10 46 38 pm

### CODE REVIEW

**Comment by hugbed** [comment]
I just realized that the transactions for your current wallet are not blue anymore.
I don't have time to fix this now and will fix this soon.

Something with:
```
	if(txn.source === coinsClient.wallet_id)
	{
		txnElement.find('#source-address').attr('class', 'my-wallet-id'); // <--- HERE
	}
	
	txnElement.find('#recipient-address').text(txn.recipient.substring(0, 15) + "...");
	txnElement.find('#recipient-address').attr('title', txn.recipient);
	
	if(txn.recipient === coinsClient.wallet_id)
	{
		txnElement.find('#recipient-address').attr('class', 'my-wallet-id'); // <--- HERE
	}
```

**Comment by jordsti** [comment]
Nice work ! Which University ?

**Comment by hugbed** [comment]
Sherbrooke, team Gordon!

**Comment by DrPandemic** [comment]
🥇

**Comment by jordsti** [comment]
You've got 25 coins for that. But there's a bugs with the transaction listing. They aren't shown at the moment. When this will be fix, I'll update the wallet manager running on cscoins.2017.csgames.org.

**Pull request merged**
